name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildPlatforms:
      - Ubuntu
    buildSteps:
      - script: node scripts/all-npm.js i
        displayName: Install All dependencies

      - script: cd anycode && npm run compile
        displayName: Compile extension

      - script: cd anycode && npx playwright install-deps
        displayName: Install operating system dependencies

      - script: cd anycode && npm run test-server
        displayName: Test extension
