name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: ["*"]
  tags:
    include:
      - anycode.*
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildPlatforms:
      - Ubuntu
    cgSourceScanPath: $(Build.SourcesDirectory)/anycode
    workingDirectory: $(Build.SourcesDirectory)/anycode
    buildSteps:
      - script: cd anycode
        displayName: Change into "anycode" directory

      - script: npm install -ci
        displayName: Install All dependencies

      - script: npm run compile
        displayName: Compile extension

      - script: npx playwright install-deps
        displayName: Install operating system dependencies

      - script: npm run test-server
        displayName: Test extension
