name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - anycode-python.*
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildPlatforms:
      - Ubuntu
    buildSteps:
      - script: cd anycode-python && npm install
        displayName: Install dependencies
    
      - script: cd anycode && npm install
        displayName: Install dependencies (anycode)

      - script: cd anycode-python && npm run test
        displayName: Run Test Fixtures

    cgSourceScanPath: $(Build.SourcesDirectory)/anycode-python
    workingDirectory: $(Build.SourcesDirectory)/anycode-python
