name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - anycode-typescript
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: lszomoru/extension-terrapin
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: ls -al
        workingDirectory: $(Build.SourcesDirectory)
        displayName: List files

      - script: ls -al
        workingDirectory: $(Build.SourcesDirectory)/anycode-typescript
        displayName: List files

      - script: ls -al
        workingDirectory: $(Build.SourcesDirectory)/anycode
        displayName: List files

      - script: npm install --loglevel verbose
        continueOnError: true
        workingDirectory: $(Build.SourcesDirectory)/anycode-typescript
        displayName: Install dependencies
        # env:
        #   NPM_CONFIG_USERCONFIG: $(Agent.TempDirectory)/.npmrc

      - script: npm install --loglevel verbose
        continueOnError: true
        workingDirectory: $(Build.SourcesDirectory)/anycode
        displayName: Install dependencies (anycode)
        # env:
        #   NPM_CONFIG_USERCONFIG: $(Agent.TempDirectory)/.npmrc

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)/anycode-typescript
        displayName: Run Test Fixtures

    ghCreateTag: true
    ghTagPrefix: anycode-typescript.v

    publishExtension: ${{ parameters.publishExtension }}

    tsa:
      enabled: true
      options:
        codebaseName: 'devdiv_$(Build.Repository.Name)'
        serviceTreeID: 'c4cd3983-4977-4bcd-931f-a9822d2e950c'
        instanceUrl: 'https://devdiv.visualstudio.com/defaultcollection'
        projectName: 'DevDiv'
        areaPath: "DevDiv\\VS Code (compliance tracking only)\\Visual Studio Code Language Extensions"
        notificationAliases:
          - 'stbatt@microsoft.com'
          - 'lszomoru@microsoft.com'
          - 'jrieken@microsoft.com'

    cgSourceScanPath: $(Build.SourcesDirectory)/anycode-typescript
    workingDirectory: $(Build.SourcesDirectory)/anycode-typescript
